/-
  Infrastructure.lean

  Root module for infrastructure files that prove axioms and provide utilities.
  Import this to access all infrastructure theorems.
-/

import Infrastructure.CohomologyInfra
import Infrastructure.GraphTheoryUtils
import Infrastructure.H1BridgeProofs
import Infrastructure.AxiomElimination
import Infrastructure.GameTheoryBridge
import Infrastructure.GameTheoryProofs
import Infrastructure.SmallGraphsFixed
import Infrastructure.GraphComposition
import Infrastructure.SmallComplexH2
import Infrastructure.TreeGraphInfra
import Infrastructure.TreeAuthCoreProofs
import Infrastructure.ComponentCountingBasic
import Infrastructure.ExtendedGraphInfra
import Infrastructure.TreeAcyclicityComplete
import Infrastructure.FairnessComplexH1
import Infrastructure.GameAxiomReplacements
import Infrastructure.BridgeAxiomReplacements
import Infrastructure.FairnessAxiomReplacements
import Infrastructure.CohomologyAxiomReplacements
import Infrastructure.CriticalPointsAxiomReplacements
import Infrastructure.TreeAuthAxiomReplacements
