import Perspective.ValueSystem
import Perspective.Alignment
import Perspective.ValueComplex
import Perspective.AlignmentEquivalence
import Perspective.AlignmentTheorem
import Perspective.ImpossibilityStrong
import Perspective.ConflictLocalization
